### ISSUE TITLE
error uploading notes

### ISSUE THREAD

**Issue by jotech** [robert7/nixnote2#43] opened 2018-10-14 18:59 UTC
I'm having difficulties to synchronize some notes with the evernote server:

```
INFO  2018-10-14 20:48:54.307 src/main.cpp:277 NixNote 2.1.0-beta4j-8e3ec46c, build at Oct 14 2018 at 20:38:11, with Qt 5.11.1 running on 5.11.1
INFO  2018-10-14 20:48:54.307 src/main.cpp:280 To get more detailed startup logging use --logLevel=1
ERROR 2018-10-14 20:49:50.866 src/communication/communicationmanager.cpp:497 Exception stacktrace:
ERROR 2018-10-14 20:49:50.870 src/communication/communicationerror.cpp:86 "EDAMUserException[ENML_VALIDATION]: EDAMUserException: ENML_VALIDATION parameter=Attribute \"data-hook\" must be declared for element type \"span\"."
ERROR 2018-10-14 20:49:50.870 src/threads/syncrunner.cpp:1180 "Error uploading note:Ericsson2017 - Peak: Secrets from the New Science of Expertise"
[[ ... same error for different notes ]
```
I'm running debian 4.17.0-1 and the problem exists with the official baumgarr version, too.

Do you have any clue what I can try? The affected notes seems very normal from what I can see in the gui. Thanks in advance!

**Comment by robert7** [comment] 2018-10-15 07:13
Hi
the error message say there is tag `<span data-hook="..." ....>` in your note and the attribute is invalid for Evernote.

In the last development version "2.1.0-beta4l" I did improvement of the html cleanup. This case (among many similar) should be included in the fix.
The dev version can be downloaded here https://github.com/robert7/nixnote2/releases/tag/continuous-develop

This particular fix changes critical part of the code handling the sync with Evernote. I did quite a lot testing myself, so I'm I think it should work OK, but it better to be a bit cautious at beginning. It would be nice if you can do few test for me, to confirm, the new version works as indented. Following cases needs to be tested:
1. standard notes without attachments (with html)
2. note with image attachments
3. non image attachments (like zip, pdf, etc)
4. note encryption (select part of the note, then right click "Encrypt selected text")

You should edit the note, sync, then verify its OK and possible also check content with evernote web client.

**Comment by jotech** [comment] 2018-10-15 08:11
I tested it with the latest development version 8e3ec46ce1e86bca86ec2a34c6877a8ee58c8daf when the error occurred. But the note was created with baumgarr nixnote.
The note itself has only some links and minor text, no attachment and images or encryption. Is there a way to see the plain html of a note?

**Comment by robert7** [comment] 2018-10-15 09:15
>... Is there a way to see the plain html of a note?

Yes. View/Show note source (Ctrl-Shift-S)

Use the "2.1.0-beta4l" version.
Doesn't matter that the note was created with older nixnote. You just need to edit it (some trivial change is enough). This will trigger the conversion from HTML to ENML (ENML is the XML data format Evernote is using internally).

Regarding the testing - only the conversion from HTML to ENML was modified. So if you do some tests, only the notes you manually edit get changed. So even if there were a bug, only the notes you change manually, could be affected. So if you use some temporary notes for the tests, you are safe. 
For the test you can duplicate any of your existing notes (by right click/duplicate note) then do changes, check, then delete the duplicate.

**Comment by jotech** [comment] 2018-10-15 14:53
great thanks! I can see the span tag now :)
But if I try to change the note, then nixnote crashes:
```
./appdir/usr/bin/nixnote2 
INFO  2018-10-15 16:44:57.656 src/main.cpp:277 NixNote 2.1.0-beta4j-8e3ec46c, build at Oct 14 2018 at 20:38:11, with Qt 5.11.1 running on 5.11.1
INFO  2018-10-15 16:44:57.656 src/main.cpp:280 To get more detailed startup logging use --logLevel=1
Could not parse stylesheet of object 0x56508e99d0b0
Could not parse stylesheet of object 0x56508e99d0b0
Could not parse stylesheet of object 0x56508e99d0b0
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
INFO  2018-10-15 16:45:13.340 src/html/enmlformatter.cpp:311 ===== Rebuilding note ENML
ERROR 2018-10-15 16:45:13.340 src/html/enmlformatter.cpp:283 Tidy FAILED: severe error occurred, code=-1
Error: signal 11:
./appdir/usr/bin/nixnote2(_Z13fault_handleri+0x35)[0x56508d6a7c85]
/lib/x86_64-linux-gnu/libc.so.6(+0x35fc0)[0x7fb7acc5afc0]
/usr/lib/libtidy.so.5(tidyBufFree+0x10)[0x7fb7b1a23690]
./appdir/usr/bin/nixnote2(_ZN13EnmlFormatter8tidyHtmlE15HtmlCleanupMode+0xfb)[0x56508d90af8b]
./appdir/usr/bin/nixnote2(_ZN13EnmlFormatter15rebuildNoteEnmlEv+0x105)[0x56508d9130e5]
./appdir/usr/bin/nixnote2(_ZN14NBrowserWindow15saveNoteContentEv+0x2dc)[0x56508d7bb49c]
./appdir/usr/bin/nixnote2(_ZN7NixNote23updateSelectionCriteriaEb+0x64)[0x56508d6b1534]
./appdir/usr/bin/nixnote2(+0x41138d)[0x56508d97938d]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x76b)[0x7fb7ad45e7cb]
./appdir/usr/bin/nixnote2(_ZN8LineEdit14buildSelectionEv+0x2a0)[0x56508d79c2f0]
./appdir/usr/bin/nixnote2(+0x4215f5)[0x56508d9895f5]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x76b)[0x7fb7ad45e7cb]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x2997d5)[0x7fb7b12eb7d5]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x76b)[0x7fb7ad45e7cb]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN18QWidgetLineControl15processKeyEventEP9QKeyEvent+0x125)[0x7fb7b12f1bc5]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN9QLineEdit13keyPressEventEP9QKeyEvent+0x1a)[0x7fb7b12e503a]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x7f7)[0x7fb7b11efdf7]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN9QLineEdit5eventEP6QEvent+0xaa)[0x7fb7b12eb04a]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x81)[0x7fb7b11b14a1]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x1199)[0x7fb7b11b9a69]
./appdir/usr/bin/nixnote2(_ZN11Application6notifyEP7QObjectP6QEvent+0x2a)[0x56508d69b07a]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x179)[0x7fb7ad435589]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1bae89)[0x7fb7b120ce89]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x81)[0x7fb7b11b14a1]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x210)[0x7fb7b11b8ae0]
./appdir/usr/bin/nixnote2(_ZN11Application6notifyEP7QObjectP6QEvent+0x2a)[0x56508d69b07a]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x179)[0x7fb7ad435589]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate15processKeyEventEPN29QWindowSystemInterfacePrivate8KeyEventE+0x168)[0x7fb7ade9f308]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE+0x115)[0x7fb7adea4985]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0xab)[0x7fb7ade7f0db]
Forcing save

```
I uploaded the html code of the corresponding note in case this helps.
[error_note.txt](https://github.com/robert7/nixnote2/files/2479244/error_note.txt)

**Comment by robert7** [comment] 2018-10-15 15:12
For me it worked fine (with the html you provided).
pls try the develop version AppImage from https://github.com/robert7/nixnote2/releases/tag/continuous-develop
I see from log, you used "beta4j" but you need "beta4l" - the ENML fix is only in "beta4l"

did you compile the binary yourself?

**Comment by robert7** [comment] 2018-10-15 15:13
and you can edit the HTML using view source - but you need not to do it - the app should handle it itself

**Comment by jotech** [comment] 2018-10-16 09:13
good point, I compiled the master branch. Did it again for feautre/rc1 but it still crashes when I try to edit this particular note: 
```
INFO  2018-10-16 11:08:09.598 src/main.cpp:277 NixNote 2.1.0-beta4l-82d14ca7, build at Oct 16 2018 at 11:01:18, with Qt 5.11.1 running on 5.11.1
INFO  2018-10-16 11:08:09.598 src/main.cpp:280 To get more detailed startup logging use --logLevel=1
Could not parse stylesheet of object 0x5584c39070b0
Could not parse stylesheet of object 0x5584c39070b0
Could not parse stylesheet of object 0x5584c39070b0
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
INFO  2018-10-16 11:08:10.313 src/nixnote.cpp:208 encrypt available
INFO  2018-10-16 11:09:55.067 src/html/enmlformatter.cpp:344 enml-cleanup: ===== rebuilding note ENML
ERROR 2018-10-16 11:09:55.067 src/html/enmlformatter.cpp:316 enml-cleanup: tidy FAILED: severe error occurred, code=-1
Error: signal 11:
./appdir/usr/bin/nixnote2(_Z13fault_handleri+0x35)[0x5584c30edcb5]
/lib/x86_64-linux-gnu/libc.so.6(+0x35fc0)[0x7fe3de336fc0]
/usr/lib/libtidy.so.5(tidyBufFree+0x10)[0x7fe3e30ff690]
./appdir/usr/bin/nixnote2(_ZN13EnmlFormatter8tidyHtmlE15HtmlCleanupMode+0xeb)[0x5584c3350e8b]
./appdir/usr/bin/nixnote2(_ZN13EnmlFormatter15rebuildNoteEnmlEv+0x10e)[0x5584c335953e]
./appdir/usr/bin/nixnote2(_ZN14NBrowserWindow15saveNoteContentEv+0x2f0)[0x5584c3200040]
./appdir/usr/bin/nixnote2(_ZN7NixNote12saveContentsEv+0x93)[0x5584c30f14f3]
./appdir/usr/bin/nixnote2(_ZN7NixNote8openNoteEb+0x15)[0x5584c30f5d95]
./appdir/usr/bin/nixnote2(+0x4115a2)[0x5584c33bf5a2]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x76b)[0x7fe3deb3a7cb]
./appdir/usr/bin/nixnote2(_ZN10NTableView8openNoteEb+0x42)[0x5584c33d3c32]
./appdir/usr/bin/nixnote2(_ZN10NTableView16openSelectedLidsEb+0x214)[0x5584c322c084]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x1d8)[0x7fe3e28cb7d8]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN6QFrame5eventEP6QEvent+0x1e)[0x7fe3e296ee8e]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN17QAbstractItemView13viewportEventEP6QEvent+0x1ab)[0x7fe3e2ae01ab]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN23QCoreApplicationPrivate29sendThroughObjectEventFiltersEP7QObjectP6QEvent+0x9b)[0x7fe3deb1129b]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x71)[0x7fe3e288d491]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x458)[0x7fe3e2894d28]
./appdir/usr/bin/nixnote2(_ZN11Application6notifyEP7QObjectP6QEvent+0x2a)[0x5584c30e10aa]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x179)[0x7fe3deb11589]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Eb+0x1a9)[0x7fe3e2894029]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1b8314)[0x7fe3e28e6314]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1bae9e)[0x7fe3e28e8e9e]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x81)[0x7fe3e288d4a1]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x210)[0x7fe3e2894ae0]
./appdir/usr/bin/nixnote2(_ZN11Application6notifyEP7QObjectP6QEvent+0x2a)[0x5584c30e10aa]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x179)[0x7fe3deb11589]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE+0x74b)[0x7fe3df57eaab]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE+0x135)[0x7fe3df5809a5]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0xab)[0x7fe3df55b0db]
Forcing save

```

**Comment by robert7** [comment] 2018-10-16 09:56
:) You are welcome, if you want to compile the app yourself, but then I can't help you much, when the app crashes. As you see, the crash happens then the external dynamically linked tidy library is called. No idea which version of the library are you using etc... There can be many factors..

As I wrote yesterday - I suggest you try develop version AppImage from https://github.com/robert7/nixnote2/releases/tag/continuous-develop

With that for me it worked fine using the HTML of the note you provided. When you compile yourself, you are bit on your own to analyse why it crashes.

**Comment by jotech** [comment] 2018-10-16 11:12
I see thanks for pointing this out :)
I tried the image and it is not crashing anymore, great thank you!
When I do the sync there are still some notes which seem to cause problems
```
ERROR 2018-10-16 13:02:48.618 src/communication/communicationerror.cpp:86 "EDAMUserException[ENML_VALIDATION]: EDAMUserException: ENML_VALIDATION parameter=Attribute \"id\" must be declared for element type \"a\"."
ERROR 2018-10-16 13:02:48.839 src/communication/communicationerror.cpp:86 "EDAMUserException[BAD_DATA_FORMAT]: EDAMUserException: BAD_DATA_FORMAT parameter=ResourceAttributes.sourceURL"
```
First [note1](https://github.com/robert7/nixnote2/files/2482722/note1.txt) was copied from a web page and the second [note2](https://github.com/robert7/nixnote2/files/2482721/note2.txt) includes some latex.

**Comment by robert7** [comment] 2018-10-16 11:37
note1: is a bug; thx for example. i'll fix
note2: I can't reproduce; but I'll recheck the latex code - this is one of the last things I did checked in the ENML code - could you maybe describe steps how to reproduce without the "note2" html? as I don't use latex :) and have no clue how it is indented to work

**Comment by jotech** [comment] 2018-10-16 13:17
Thanks for fixing :)
When I create a new note, right click -> insert latex formula and then adding this text:
```latex
\text{Sei } dimV=n\lt\infty \text{ und } L\,:\,V\rightarrow W \text{ linear, dann gilt:}\\
dim \,\text{Kern}\, L + dim\, \text{Bild}\, L = n
```
then the new note is causing and error when synchronizing
```
ERROR 2018-10-16 15:14:30.113 src/communication/communicationerror.cpp:86 "EDAMUserException[BAD_DATA_FORMAT]: EDAMUserException: BAD_DATA_FORMAT parameter=ResourceAttributes.sourceURL"
```

**Comment by robert7** [comment] 2018-10-16 15:19
I fixed the problem with "Attribute \"id\" must be declared for element type \"a\"" (will be available tomorrow).

I looked at the Latex integration - the whole old implementation is very "hacky".  It creates gif rendering of the LaTex formula. but then the upload seems to fail (BAD_DATA_FORMAT parameter=ResourceAttributes.sourceURL).

I'm not sure how it supposed to work. In the v2.0 the functionality wan't very stable either (upload worked, but e.g. edit not). So unfortunately currently for me the "latex integration" is "won't fix" ... if anyone want to have it ... pull request is welcome.

**Comment by robert7** [comment] 2018-10-16 16:39
For the improvement of LaTeX integration in create new issue.
The rest should work. So I'm closing this. 
Pls retest with "2.1.0-beta4k" (should be available in a while) and let me know if you find any more problems related to sync.

**Closed by robert7** 2018-10-16 16:39 UTC
Labels: bug

**Comment by jotech** [comment] 2018-10-17 09:04
This fix for the attribute id works quite well, thank you a lot!
Concerning the latex issue I will stick to the new issue.

**Comment by robert7** [comment] 2018-10-17 09:08
>Concerning the latex issue I will stick to the new issue.

if will try to fix, later. I don't use LaTex but it seems interesting feature (I tried yesterday for first time)

**Comment by robert7** [comment] 2018-12-16 10:34
![screen_20181216_02](https://user-images.githubusercontent.com/1135218/50052580-6f590200-0126-11e9-8be0-d1d38444ba4e.png)
the mentionen LaTeX formula should work now (2.1.2-f)

**Comment by jotech** [comment] 2019-02-12 14:36
great it is working, thanks!
