### ISSUE TITLE
PDFs are not opening with default application

### ISSUE THREAD

**Issue by simonszu** [robert7/nixnote2#111] opened 2019-06-19 06:40 UTC
I am referencing Issue https://github.com/robert7/nixnote2/issues/57 since i got a similar behaviour. 

PDFs are opened in Inkscape from nixnote2. This is strange, since the default mime association from `$HOME/.config/mimeapps.list` is for PDF:

```
[Added Associations]
application/pdf=okularApplication_pdf.desktop;qpdfview.desktop;pdfmod.desktop;FoxitReader.desktop;foxitreader.desktop;acroread.desktop;
```
Inkspace isn't even listed here. You mentioned a specific Qt5-Function for opening files in the linked issue, so i checked other Qt Applications like qtfm and Dolphin - a double-click on PDF files in these applications opens them in Okular, which is my system-wide default PDF reader. It's only nixnote2 which has a different behaviour. 

I have Version: 2.1.3-2b95eae6 of nixnote2 installed, it is installed via the nixnote2-git package from Arch Linux AUR.

**Comment by robert7** [comment] 2019-07-30 17:14
Hi @simonszu 
sorry for late answer...
What Nixnote does is calling Qt method [QDesktopServices::openUrl](https://doc.qt.io/archives/qt-5.5/qdesktopservices.html#openUrl) with local file path e.g. /home/robert7/.nixnote/db-2/dba/43150.pdf

In my case I have configured "Foxit Viewer" and it seems to work fine...

As the url is opened by Qt ... and the call is not customized... I'm aftraid, I can't do anything in Nixnote to modify it. It looks like something specific to your local system...

Example:
![screen_20190730_14](https://user-images.githubusercontent.com/1135218/62150335-095c6c00-b2fe-11e9-91bd-421304594b15.png)

So from my viewpoint yout ticket is duplicate of #57

**Closed** 2019-08-07 12:20 UTC
