### ISSUE TITLE
Cursor jumps to search after sync

### ISSUE THREAD

**Issue by adamoxford** [robert7/nixnote2#59] opened 2018-11-25 07:09 UTC
Using Ubuntu 18.10 - after a sync is performed the cursor jumps to the search box (so if you're in the middle of writing you lose focus on the note). 

Changing values in Settings>Search doesn't seem to affect this.

**Comment by adamoxford** [comment] 2018-11-25 07:11
Ignore this - noticed it's a duplicate of #7

**Comment by robert7** [comment] 2018-11-26 19:43
No, actually its not a duplicate. #7 was about the "sync notification" (which I don't use and which I think are useless ... so its no problem to let them turned off).
But the problem you describe is also present with notifications off.

I did not notice, because I usually sync, when I'm finished with the note. But the cursor jump is annoying. I will try to fix it. Thx for reporting.

**Comment by robert7** [comment] 2018-12-14 14:42
Should be now fixed (in 2.1.2-d). Let me know if you can still reproduce.

**Closed by robert7** 2018-12-14 14:42 UTC
Labels: bug-minor
