### ISSUE TITLE
Sort does not work in note list.

### ISSUE THREAD

**Issue by timoc** [robert7/nixnote2#9] opened 2018-08-24 13:53 UTC
When clicking on the table header in the notebook list (wide or narrow), the table does not sort on that headline. It sorts only on the last change.

**Comment by robert7** [comment] 2018-08-25 13:39
You mean "note list" not "notebook list" right?

Yes. The sorting is now fixed (so you can have you favorite sorting, if your favorite is by "date last change" - like it's mine :) ..). The reason is: I needed multi column sort for the "[sort by relevance feature](https://github.com/robert7/nixnote2/wiki/Results-sorted-by-relevance-to-search-query)" and still did not have time to improve - as I don't really need it.

But I plan to improve this in near futute.

**Comment by timoc** [comment] 2018-08-25 14:59
I need it because in certain notebooks i prefix the noe with a number to indicate chapter.

**Comment by nopivnick** [comment] 2018-08-25 17:07
> i prefix the no[t]e with a number

as do I.

I put the date at the front of the title field (e.g., "2018-08-25 » phone w/ X re: Y") because it's a clean way to 'cluster' notes by 'event' in any given notebook using sort alphabetically rather than sort by date created which is unreliable, especially if I create the note after the fact (i.e., the next day).

**Comment by robert7** [comment] 2018-08-25 17:32
OK. I'll fix this with high prio.

**Comment by timoc** [comment] 2018-08-27 07:37
I was doing this for meeting notes, but I thought you could update the create time, and was planning to batch that change to those notes. Is that not the case?

**Comment by robert7** [comment] 2018-08-27 11:58
yes. you should be able to update the created time

**Comment by MRC01** [comment] 2018-08-31 20:27
I noticed this bug myself (left clicking on column header doesn't sort). The older trunk version used to do this, so the feature was somehow lost or dropped.

**Comment by robert7** [comment] 2018-09-01 13:06
@MRC01 how/why and what's the plan is already explained in this thread :)

**Comment by robert7** [comment] 2018-09-04 18:30
I added the sort option. its in the menu View; I added all the combinations I seen as meaningful. In case I missen some relevant use case, I can add it later.
Clicking on header isn't easily possible, as the sort needs to be multi-column.

![screen_20180904_05](https://user-images.githubusercontent.com/1135218/45050292-2ef6dc00-b081-11e8-8515-715608fd91bb.png)

The fix is present in "beta-3" (the binary is on [Dropbox folder](https://github.com/robert7/nixnote2/releases); I'll do few more testing and will publish in on releases).

**Comment by MRC01** [comment] 2018-09-04 19:12
Multi-column sorts are nice, but why must all sorts be multi-column? In the prior version of Nixnote, clicking on a column header does a single-column sort. It's simple and quick.

**Comment by robert7** [comment] 2018-09-05 09:52
@MRC01 Sort needs to be multi-column because of the [relevance sort](https://github.com/robert7/nixnote2/wiki/Results-sorted-by-relevance-to-search-query). Not all sort options are multi-column, there are also few single column.

Of course - multi column sort with clicking on column titles also could be done - its open source - you welcome to contribute it. Pull requests are welcome. For me its enough like this,

**Comment by rodelrod** [comment] 2018-09-05 17:06
Hi @robert7, thanks for picking up the work on Nixnote, it's very important for Linux users! 

Just to add another data point: I'd like to use your fork because there's a bunch of nice improvements, but I'm afraid that my current workflow depends on the ability to sort on click; much more so than relevance sort, although it looks like a nice feature. Would be willing to forfeit the latter for the former if there was a switch.

If and when I can liberate the time to pick up enough C++/Qt, I'll be happy to help, but realistically it won't happen for a while...

**Comment by robert7** [comment] 2018-09-05 19:13
>thanks for picking up the work on Nixnote

Actually, it wasn't my intention at all. My intention was to contribute few new features, which I personaly need and use the app for myself. Then after adding the few features, I discovered, the the upstream is dead, I continued to make the program someway usable for other users. I thought, there will be a lot of interest. You may imagine, that I have a lot of time for this project. But the truth is, I actually have **none**. I managed someway to "create" a lot of time since June, when I started this as a kind of "open source experiment". That means I temporarily shifted the priorities from other things.

I previously did not any open source and it was something I wanted to try. So I actually spend really a lot of time by bringing the app where it is now (I spend maybe 80% of time for stuff I actually wouldn't need, if I just would want to use app for myself). I did not do C++ for like 15 yrs and didn't know anything about Qt.

> ...it's very important for Linux users

Really? Yes, I also though so. But actually now I'm not that sure anymore. Because for the new v2.1 there are currently like 7 to 11 users. This is quite a fail, given how much time I spend with it. But the app works very well for me, I use it daily a lot. So I will keep it like it is, I will fix any important bugs, which I will be able to fix. But given almost no real interest from users... there is little motivation for more.

I think the problem is, all google links lead to the upstream repository, where the existing and new potential users just see project is dead and they go away. Almost none bothers to check if there is another active fork.

**Comment by rodelrod** [comment] 2018-09-05 19:58
Yes there’s a discoverability issue. I only found your fork after hours of digging through issues in the main repository and seeing your comments there. Even today I was looking for it and had to browse through the list of forks in the upstream repo. 

I do believe that Nixnote is important for Linux users. I’ve spent countless hours getting the Evernote Windows client to work in Linux with the right incantation of wine/EN versions and tricks (possible but exhausting). Also countless hours looking for alternatives to Evernote that work both on Linux and mobile with the minimal viable set of features (there are none as far as I can tell). I probably should have spent that time learning Qt instead. Nixnote is the only serious Linux EN client that is full-featured/performant/reliable enough for daily usage.  

Thank you for your work, what you’ve done already is super useful and will get picked up sooner or later.

**Comment by MRC01** [comment] 2018-09-05 21:04
Ditto to rodelrod's comments, and thanks to Robert.
I've been programming in C since the 1980s. Haven't done QT, but have done Windows & OS/2 WM_Message apps, MFC and OWL, and Java Swing back in the day. I tried building NixNote a couple of years ago. It led to dependency hell in QT and Ubuntu versions. I didn't have time to sort it out.
Robert, if you've got a version that builds clean on Ubuntu 16, I'm willing to take another look. My Ubuntu 16 systems seems to have come with QT 5.5. My Ubuntu 18 system has version 5.9.

**Comment by robert7** [comment] 2018-09-06 09:18
@MRC01 yes it builds easily with Ubuntu 16.04 and also 18.04 (I'm using 18.04 now and had 16.04 until recently)

**Comment by robert7** [comment] 2018-09-06 11:13
the sorting works now; so I'm closing this now

**Closed by robert7** 2018-09-06 11:13 UTC
Labels: enhancement
