### ISSUE TITLE
I can't sync my notes

### ISSUE THREAD

**Issue by AiratHalitov** [robert7/nixnote2#154] opened 2020-05-21 18:51 UTC
## Logs
```
INFO  2020-05-21 23:41:57.380 src/main.cpp:304 NixNote 202005061503~2.1.6~ubuntu16.04.1, build at May  6 2020 at 15:03:12, with Qt 5.5.1 running on 5.5.1
INFO  2020-05-21 23:41:57.380 src/main.cpp:307 To get more detailed startup logging use --logLevel=1
ERROR 2020-05-21 23:41:59.162 src/communication/communicationmanager.cpp:537 Exception stacktrace:
ERROR 2020-05-21 23:41:59.163 src/communication/communicationerror.cpp:88 "EDAMSystemException[code=768]: EDAMSystemException: UNRECOGNIZED_ERROR_CODE"
ERROR 2020-05-21 23:42:12.686 src/communication/communicationmanager.cpp:537 Exception stacktrace:
ERROR 2020-05-21 23:42:12.688 src/communication/communicationerror.cpp:88 "EDAMSystemException[code=768]: EDAMSystemException: UNRECOGNIZED_ERROR_CODE"
INFO  2020-05-21 23:43:09.809 src/html/enmlformatter.cpp:365 enml-cleanup: ===== rebuilding note ENML
INFO  2020-05-21 23:43:09.810 src/html/enmlformatter.cpp:319 enml-cleanup: tidy DONE: diagnostics: "line 1 column 1 - Warning: missing <!DOCTYPE> declaration; line 1 column 44 - Warning: inserting missing 'title' element; line 9 column 25 - Warning: trimming empty <ul>; line 9 column 21 - Warning: trimming empty <ul>; line 9 column 16 - Warning: trimming empty <div>; Info: Document content looks like XHTML5; Tidy found 5 warnings and 0 errors!; ; "
INFO  2020-05-21 23:43:09.814 src/html/enmlformatter.cpp:319 enml-cleanup: tidy DONE: diagnostics: "line 1 column 1 - Warning: missing <!DOCTYPE> declaration; line 1 column 1 - Warning: inserting missing 'title' element; Info: Document content looks like XHTML5; Tidy found 2 warnings and 0 errors!; ; "
INFO  2020-05-21 23:43:09.814 src/html/enmlformatter.cpp:440 enml-cleanup: ===== finished rebuilding note ENML in 5 ms
ERROR 2020-05-21 23:43:10.309 src/communication/communicationmanager.cpp:537 Exception stacktrace:
ERROR 2020-05-21 23:43:10.314 src/communication/communicationerror.cpp:88 "EDAMSystemException[code=768]: EDAMSystemException: UNRECOGNIZED_ERROR_CODE"
INFO  2020-05-21 23:43:14.818 src/html/enmlformatter.cpp:365 enml-cleanup: ===== rebuilding note ENML
INFO  2020-05-21 23:43:14.819 src/html/enmlformatter.cpp:319 enml-cleanup: tidy DONE: diagnostics: "line 1 column 1 - Warning: missing <!DOCTYPE> declaration; line 1 column 44 - Warning: inserting missing 'title' element; Info: Document content looks like XHTML5; Tidy found 2 warnings and 0 errors!; ; "
INFO  2020-05-21 23:43:14.827 src/html/enmlformatter.cpp:319 enml-cleanup: tidy DONE: diagnostics: "line 1 column 1 - Warning: missing <!DOCTYPE> declaration; line 1 column 1 - Warning: inserting missing 'title' element; Info: Document content looks like XHTML5; Tidy found 2 warnings and 0 errors!; ; "
INFO  2020-05-21 23:43:14.827 src/html/enmlformatter.cpp:440 enml-cleanup: ===== finished rebuilding note ENML in 9 ms
ERROR 2020-05-21 23:43:15.320 src/communication/communicationmanager.cpp:537 Exception stacktrace:
ERROR 2020-05-21 23:43:15.324 src/communication/communicationerror.cpp:88 "EDAMSystemException[code=768]: EDAMSystemException: UNRECOGNIZED_ERROR_CODE"
ERROR 2020-05-21 23:45:37.621 src/communication/communicationmanager.cpp:537 Exception stacktrace:
ERROR 2020-05-21 23:45:37.624 src/communication/communicationerror.cpp:88 "EDAMSystemException[code=768]: EDAMSystemException: UNRECOGNIZED_ERROR_CODE"

```

## Steps to reproduce the problem (or [log file](https://github.com/robert7/nixnote2/wiki/HowTo---Add-log-file-to-the-github-issue))

  1. Create new note
  1. Try to sync 
  1. Get an Error

## Specifications

NixNote `202005061503~2.1.6~ubuntu16.04.1`, build at May  6 2020 at 15:03:12, with Qt 5.5.1 running on 5.5.1

**Comment by robert7** [comment] 2020-05-27 07:15
this is duplicate of #142 (error code not recognised)
and #152 (you have garbage in your node and you need to clean it up)

**Closed** 2020-05-27 07:15 UTC

**Comment by AiratHalitov** [comment] 2020-05-27 07:49
@robert7 
The problem was solved after editing in web version of Evernote

**Comment by robert7** [comment] 2020-05-27 10:46
fine. 
it should be exception, when the HTML is not properly cleaned up
most of the cases should be handled automatically
