### ISSUE TITLE
Does not sync last tag removal

### ISSUE THREAD

**Issue by memfiz** [robert7/nixnote2#96] opened 2019-04-04 20:07 UTC
## Expected vs. actual behavior

If you remove the last tag from a note and sync, the note without any tags should be synchronized to the evernote.
In reality only local version of NixNote where the tag was removed shows the note without tags. Evernote still stores the tag attached to the note.

## Steps to reproduce the problem (or [log file](https://github.com/robert7/nixnote2/wiki/HowTo---Add-log-file-to-the-github-issue))

  1. create a note with some tag
  1. sync it and check that in evernote web/client it is tagged appropriately
  1. remove the tag from the note in NixNote, so the note is without any tags
  1. sync it and check in evernote web/client. the note is still tagged.  

## Specifications

  - Version: 201903260816, 2.1.3, ubuntu18.04.1

**Comment by robert7** [comment] 2019-04-05 08:07
weird... I could reproduce 
I will try to fix it later

**Comment by robert7** [comment] 2019-05-21 15:17
@memfiz 
Hi, the problem is fixed in version  2.1.4-c

**Closed by robert7** 2019-05-21 15:17 UTC
Labels: bug

**Comment by memfiz** [comment] 2019-05-22 06:36
Hi, thanks! I've upgraded and tested, it works now!
