### ISSUE TITLE
Sync error "server replied: OK"

### ISSUE THREAD

**Issue by greenie537** [robert7/nixnote2#151] opened 2020-04-24 01:58 UTC
Sync error log
INFO  2020-04-24 13:49:46.757 src/main.cpp:287 NixNote 2.1.5-f76068eb, build at Mar 13 2020 at 13:54:16, with Qt 5.14.1 running on 5.14.2
WARN  2020-04-24 13:54:16.383 src/qevercloud/QEverCloud/src/http.cpp:100 QEverCloud.http.ReplyFetcher.onError: "Error transferring https://www.evernote.com/edam/user - server replied: OK"
WARN  2020-04-24 13:54:16.383 src/qevercloud/QEverCloud/src/http.cpp:153 QEverCloud.http.simpleDownload error "Error transferring https://www.evernote.com/edam/user - server replied: OK"
ERROR 2020-04-24 13:54:16.383 src/communication/communicationmanager.cpp:535 Exception stacktrace:
ERROR 2020-04-24 13:54:16.384 src/communication/communicationerror.cpp:86 "StdException[16]: Error transferring https://www.evernote.com/edam/user - server replied: OK"

Specifications
  - Qt version 5.14.2.
  - Version: 2.1.5-f76068eb

Cheers
Just started today.

**Comment by swordgreen** [comment] 2020-04-24 04:15
The same problem here with Version: 202003110020~2.1.5~ubuntu16.04.1.

**Comment by Meliowant** [comment] 2020-04-24 06:31
Same problem on the Debian testing/unstable with the version: 2.1.5+dfsg1-1

**Comment by MKaras93** [comment] 2020-04-24 07:00
Same problem with `202003110017~2.1.5~ubuntu18.04.1`

**Comment by kgolding** [comment] 2020-04-24 07:00
Same problem here on 201910160846~2.1.5~ubuntu19.04.1
Have chatted with Evernote who did admit to making a "maintenance release" a couple of days ago. Also, notice that the mobile app popped up a prompt to confirm my email address so I wonder if that's related?

**Comment by MKaras93** [comment] 2020-04-24 07:05
No prompts on my mobile app. And I'm 100% sure it worked fine yesterday in the morning, not sure about later hours - I've noticed it just now.

**Comment by wivory** [comment] 2020-04-24 09:01
I've seen this in past 24 hours, with 202003110017~2.1.5~ubuntu18.04.1.  I removed authorization for my account in Nixnote then hit 'sync' to get the prompt to reauthorize.  It now appears to be syncing ok again so hopefully that will work for others too.

**Comment by robert7** [comment] 2020-04-24 09:11
Yes I can confirm. Everyone seems need to reauthorize once. It seems to be some server-side change from Evernote itself. 

So go to menu "File/User Account Maintenance" then select "Remove Authorization".
Then try Sync - it will prompt for username/pwd and you should be good to go.

**Comment by robert7** [comment] 2020-04-24 09:43
Update: unfortunately for me the problem reappeared after nixnote restart... so let see... maybe its some kind of hiccup on Evernote side..

**Comment by MKaras93** [comment] 2020-04-24 09:57
If it's Authorization issue, then it's really weird that Evernote returns HTTP OK. But I can confirm, reauthorizing solved the problem, at least for now.

**Comment by dpodolskiy** [comment] 2020-04-24 18:42
Not solved; multiple re-authorizations and re-synchronizations of the whole library of notes, the issue eventually reappeared every time

**Comment by miknuc** [comment] 2020-04-25 09:44
Same here (Version: 2.1.5-b-6e1ef20,  Ubuntu 19.10).
Re-authorizing solves the problem until I restart the program.

**Comment by ra3ggi** [comment] 2020-04-25 16:27
The same problem in all versions of the program. Re-authorization helps. But after rebooting the program, there is no synchronization again. (MXLinux 19.1)

**Comment by d1vanov** [comment] 2020-04-25 17:51
I've made [a change](https://github.com/d1vanov/QEverCloud/commit/012425c98e52406fc5f3aa69750eba84b931a5a3) in QEverCloud to ignore this particular weird error and it seems to help. I'd recommend to try porting this fix into QEverCloud sources within Nixnote2's repo.

**Comment by woook** [comment] 2020-04-26 09:43
Re-authorising is a workaround but only lasts a few hours before the issue recurs for me (latest snap).

**Comment by miknuc** [comment] 2020-04-26 11:36
My program is up now for > 30h and synchronization still works.
Michael

woook <notifications@github.com> schrieb am So., 26. Apr. 2020, 11:43:

**Comment by jpinedaa** [comment] 2020-04-27 02:47
still having this problem, any fix yet?

**Comment by marcoben73** [comment] 2020-04-27 08:29
For me latest stable appimage works only if I start with a clean environment.
First authorization works and all subsequent synchronization.
If a quit the application it never start again, only shows the dialog with sync error and quit.
In log I found "StdException[16]: Error downloading https://www.evernote.com/edam/user - server replied: OK"

**Comment by robert7** [comment] 2020-04-27 10:00
I will later apply the fix from @d1vanov ... Dmitri thanks a lot!

Until then everyone need to reauthorize on each app restart.
If anyone is faster then me, them I gladly accept a pull request :)

**Comment by robert7** [comment] 2020-04-29 18:27
I did applied the patch from @d1vanov, but unfortunately it did not help.

Then I did a bit debugging.. It is that the Evernote Call which is done at the begin of sync [UserStore.getUser](https://dev.evernote.com/doc/reference/UserStore.html) get http response code [429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429). $29 means "Too Many Requests" which is weird here..

First line of response is "HTTP/1.1 429 OK" which explains "server replied: OK"... but not only we get 429, but also the response is blank, so just ignoring 429 code doesn't help really. 
And the response **IS NOT OK**.

I did a bit investigation why the same UserStore.getUser work after reauthorisation... it seems the reauth call sets some cookies... the cookies make the UserStore.getUser call go through..

So no idea how to fix. I hope Evernote will explain or fix the interface.

![en 2020_04_29 20_19_06](https://user-images.githubusercontent.com/1135218/80632462-9e3ff180-8a57-11ea-896b-956624a1488f.png)
<img width="1491" alt="en 2020_04_29 20_19_59" src="https://user-images.githubusercontent.com/1135218/80632496-a6982c80-8a57-11ea-9067-657e24229130.png">
<img width="1905" alt="en 2020_04_29 20_21_31" src="https://user-images.githubusercontent.com/1135218/80632522-adbf3a80-8a57-11ea-8c3f-a64e098aab4d.png">
<img width="1564" alt="en 2020_04_29 20_22_18" src="https://user-images.githubusercontent.com/1135218/80632531-b0ba2b00-8a57-11ea-9bec-85644e11a102.png">

**Comment by bwilson** [comment] 2020-04-29 19:49
I wonder if this comment is relevant:
"We solved the problem by changing URL for UserStore from https://www.evernote.com/edam/user to https://www.evernote.com//edam/user (used by official SDKs)"

I found it here: https://stackoverflow.com/questions/61393598/http-418-transport-errors-from-evernote-api

**Comment by robert7** [comment] 2020-04-30 07:13
@bwilson the linked ticket speaks about http code 418, we get 429, but I tried anyway. it doesn't seem to change anything
here some verbose debug output, the url is now changes, but we get same reply

![image](https://user-images.githubusercontent.com/1135218/80682306-82256a00-8ac2-11ea-9408-9fe5fff69440.png)

btw the current changes are in branch "feature/rs-2020-04" .. if anyone want to play with it

what is weird, that it seems, that anyone (other Evernote clients) except nixnote and quentier (both use QEvercloud) don't speak about 429 errors... at least I can't find anything relevant from last days

**Comment by d1vanov** [comment] 2020-04-30 07:20
Some folks from [this SO question](https://stackoverflow.com/questions/61404638/why-is-there-a-sudden-increase-in-ttransportexception) use official Evernote SDKs and still get 429 error codes. Evernote has definitely broken something on their side.

**Comment by robert7** [comment] 2020-04-30 07:23
@d1vanov thx for the link!

**Comment by robert7** [comment] 2020-04-30 10:28
Update: according info in https://github.com/d1vanov/quentier/issues/314 , the problematic call UserStore.getUser may not be essential at all to do a sync. So I will try to eliminate the call and see whenever it helps..

**Comment by d1vanov** [comment] 2020-04-30 10:55
It's not like it's not essential, it's just that incremental sync can get away without calling it. However, full sync does require that call so full sync still doesn't work.

As I mentioned in Quentier's issue, I'll try to do some experiments and see whether the cookie is really the culprit here. In the meantime I opened a [thread](https://discussion.evernote.com/topic/124257-calls-to-userstore-from-evernote-api-stopped-working/) at Evernote discussions. The forum is mostly for users but some Evernote employees occasionally show up there so hopefully we could get some answers from them. I encourage everyone to comment there to get the topic some attention.

**Comment by d1vanov** [comment] 2020-04-30 11:31
@iafan, hello Igor!
Sorry to bother you but could you please take a look at this issue? It seems something has changed in how Evernote servers process UserStore API calls. Could you or some of your colleagues please shed some light on this?

**Comment by robert7** [comment] 2020-04-30 13:54
I created an experimental version without the UserStore.getUser call.. and it seems to work
Please try: https://www.dropbox.com/s/hub6oxs5rfzx2qy/NixNote2-5d2238b-x86_64.AppImage?dl=0

In case you don't know, how to run the AppImage, look e.g. in the project wiki. The file should run on any recent linux and can be used parallel to the version, you have installed now (it will use the same data as the version you have installed e.g. from PPA). Just don't run both at the same time(!)

Although the change is very experimental, your data should not be at risk, as only the initialization of the sync was changed.

**Comment by george-v478** [comment] 2020-04-30 15:03
Working good so far after multiply restarts on Mint 19.3 XFCE:
INFO  2020-04-30 11:01:27.708 src/main.cpp:304 NixNote 2.1.6-rc4-5d2238b, build at Apr 30 2020 at 13:40:52, with Qt 5.5.1 running on 5.5.1

**Comment by ra3ggi** [comment] 2020-04-30 17:26
MXlinux 19.1 
A new authorization is required each time the program is loaded.:
INFO  2020-04-30 20:20:33.373 src/main.cpp:304 NixNote 2.1.6-rc4-5d2238b, build at Apr 30 2020 at 13:40:52, with Qt 5.5.1 running on 5.5.1
INFO  2020-04-30 20:20:33.373 src/main.cpp:307 To get more detailed startup logging use --logLevel=1
ERROR 2020-04-30 20:20:35.320 src/communication/communicationmanager.cpp:536 Exception stacktrace:
ERROR 2020-04-30 20:20:35.323 src/communication/communicationerror.cpp:88 "EDAMUserException[AUTH_EXPIRED]: EDAMUserException: AUTH_EXPIRED parameter=authenticationToken"

**Comment by george-v478** [comment] 2020-04-30 17:33
Try to reboot your PC.

**Comment by ra3ggi** [comment] 2020-04-30 17:41
Reboot doesn't change anything. Authorization is not memorable.

**Comment by iafan** [comment] 2020-04-30 17:56
@d1vanov thanks for tagging me. I flagged the issue with the Evernote team, as it can be indeed something that was triggered by changes on Evernote servers' side. We're investigating.

**Comment by miknuc** [comment] 2020-04-30 18:13
> I created an experimental version without the UserStore.getUser call.. and it seems to work
> Please try: https://www.dropbox.com/s/hub6oxs5rfzx2qy/NixNote2-5d2238b-x86_64.AppImage?dl=0
> 
> In case you don't know, how to run the AppImage, look e.g. in the project wiki. The file should run on any recent linux and can be used parallel to the version, you have installed now (it will use the same data as the version you have installed e.g. from PPA). Just don't run both at the same time(!)
> 
> Although the change is very experimental, your data should not be at risk, as only the initialization of the sync was changed.

Works for me!

**Comment by d1vanov** [comment] 2020-04-30 18:56
> @d1vanov thanks for tagging me. I flagged the issue with the Evernote team, as it can be indeed something that was triggered by changes on Evernote servers' side. We're investigating.

Great, thank you very much!

**Comment by robert7** [comment] 2020-05-01 07:02
@ra3ggi I'll try to fix the problem with AUTH_EXPIRED

**Comment by woook** [comment] 2020-05-01 10:12
NixNote2-5d2238b-x86_64.AppImage working here

**Comment by robert7** [comment] 2020-05-01 11:20
I did a bit more changes, it seems now to work stable. So I merged the changes in development branch. Updated version 2.1.6-rc6 is available at https://github.com/robert7/nixnote2/releases/tag/continuous-develop as AppImage, the development PPA for Ubuntu should also be updated soon.
Everyone who experienced the problem with "server replied OK" is invited to test.

@ra3ggi I could not reproduce your problem with AUTH_EXPIRED, in my case the token is always updated automatically. However I written a wiki page https://github.com/robert7/nixnote2/wiki/HowTo---Authorization-problems where there are some steps described, which may help you.

**Comment by lockie** [comment] 2020-05-01 12:00
@robert7 The 2.1.6-rc6 version works for me, thanks for taking care of this!

**Comment by pmarkaide** [comment] 2020-05-01 12:42
The 2.1.6-rc6 version works for me too on ubuntu 16.04. Many thanks!

**Comment by robert7** [comment] 2020-05-01 14:04
Ubuntu develop PPA (ppa:nixnote/nixnote2-stable) is updated with 2.1.6-rc6. If all work fine, I will next week also update the stable version.

**Comment by ra3ggi** [comment] 2020-05-01 16:24
> @ ra3ggi Я не могу воспроизвести вашу проблему с AUTH_EXPIRED, в моем случае токен >всегда обновляется автоматически. Однако я написал вики-страницу 
>[https://github.com/robert7/nixnote2/wiki/HowTo---Authorization-problems,]
>(https://github.com/robert7/nixnote2/wiki/HowTo---Authorization-problems) где описаны 
>некоторые шаги, которые могут вам помочь.

Deleted the files nixnote.conf and accounts.conf.  
After that, everything works with the new version 2.1.6-rc6. Thank you very much!

**Comment by marcoben73** [comment] 2020-05-01 20:22
The 2.1.6-rc6 version works for me too on fedora 28. Many thanks!

**Comment by d1vanov** [comment] 2020-05-02 07:26
I finally made an experiment with cookies and I can confirm that UserStore API calls start to work when you set cookies received during OAuth into either `QNetworkRequest` or into `QNetworkCookieJar` later set into `QNetworkAccessManager`. The only problem is that so far I wasn't able to restore cookies cleanly enough - in Quentier sync starts but at some point the app crashes with "Too many open files" error:
```
(quentier:10556): GLib-ERROR **: 10:14:01.322: Creating pipes for GWakeup: Too many open files
```
I suspect it is because Quentier uses latest version of QEverCloud which doesn't use single static `QNetworkAccessManager` for all request while older version used by NixNote2 does use a single instance. It seems either setting a cookie header to `QNetworkRequest` or setting `QNetworkCookieJar` to a `QNetworkAccessManager` instance causes some background operations with temporary files and when there are too many of them, it becomes a problem.

@robert7 If you want to go deeper with this issue, you could try saving cookies received during OAuth persistently and then when app restarts, set them to `evernoteNetworkAccessManager` via `QNetworkCookieJar` and `setCookieJar` method. However, there's a hope now that folks from Evernote could fix this issue on their side so we might just wait for it to happen.

**Comment by d1vanov** [comment] 2020-05-02 08:51
Update: actually, the "too many open files" issue was not related to cookies, it was purely Quentier's internal error. So cookies really are the culprit here and being able to save them on OAuth and then restore after the app is restarted seems to be the way to truly workaround the issue with UserStore API calls. I'm going to make a proper implementation of it in QEverCloud but maybe people from Evernote fix the issue on their side sooner than I'd be able to deliver.

**Comment by robert7** [comment] 2020-05-02 12:34
@d1vanov Currently I removed the UserStore.getUser call from incremental sync and it is called only before full sync and directly after reauthorization. This way app seems to work fine

**Comment by Darkle** [comment] 2020-05-05 09:00
Hey I just wanted to say thanks for fixing this. I appreciate all the work. 👍

**Comment by robert7** [comment] 2020-05-05 10:14
btw meanwhile it seems that Evernote fixed the problem (I did a retest today with older version and it worked OK), but I will leave the change active anyway as it seems that the UserStore.getUser call was unnecessary anyway

**Closed** 2020-05-05 10:17 UTC
