### ISSUE TITLE
copy in-app note link not working

### ISSUE THREAD

**Issue by jotech** [robert7/nixnote2#130] opened 2019-09-04 11:12 UTC
Sometimes copying internal note links does not work for me. Interestingly, it works fine if I use the evernote webinterface.

Steps to reproduce:
 - create new node
- insert title: ``somebody's test note``
- try to copy internal note link

I figured out that it seems to be connected to the note name! After renaming the note to ``somebodys test note`` it works again. Maybe there is an issue with some special characters like ``'`` ?

Last tried this using the latest nixnote 2.1.5-b

**Comment by robert7** [comment] 2019-09-06 12:54
You are right the problem is the apostrophe character.
I will look at it later and try to fix.
Meanwhile you can either:

-  remove the apostrophe from the title (recommended)
- use public link (but the you will be redirected to web client, this may not be what you want)

**Comment by boo-yee** [comment] 2022-08-23 12:28
Fixed by #192.

**Closed** 2023-04-17 17:11 UTC
Labels: bug
