### ISSUE TITLE
Sync halts on "EDAMSystemException[code=-1893778304]: EDAMSystemException: UNRECOGNIZED_ERROR_CODE"

### ISSUE THREAD

**Issue by stephanemouton** [robert7/nixnote2#155] opened 2020-05-21 21:08 UTC
## Expected vs. actual behavior
Synchronization with Evernote service is expected to be fully performed.
Instead, Synchronization halt and the `EDAMSystemException: UNRECOGNIZED_ERROR_CODE` is dispplayed
Log file bears the following line:
`ERROR 2020-05-21 22:40:47.371 src/communication/communicationerror.cpp:88 "EDAMSystemException[code=-1893778304]: EDAMSystemException: UNRECOGNIZED_ERROR_CODE"`

## Steps to reproduce the problem 
  1. Start Synchronization
  1. Wait until error pop up message appears.

Attached is a partial log file produced with DEBUG log level.
It is partial because personal data, note titles, are included in the log file.

## Specifications
Version from Fedora COPR repository running on Fedora 32
Version      : 2.1.6
Publication  : 1.ndias.fc32

[error_EDAMSystemException_short.zip](https://github.com/robert7/nixnote2/files/4664769/error_EDAMSystemException_short.zip)

**Comment by robert7** [comment] 2020-05-27 07:20
duplicate of #142 and #137 

as you can read in previous tickets:
.. It seems something got wrong in error code recognition in the last qevercloud update which was made in v2.1.5
so you may meanwhile try use older version (e.g. by using AppImage) e.g. 2.1.4 or 2.1.3, then you may get better error message, I will (maybe) later try to find out

in your case it could be "rate-limit" or something else

**Closed** 2023-04-17 17:06 UTC
